In [ ]:
# 1

# Importance of NumPy

# Faster than Python lists because it is implemented in C.
# Requires less memory.
# Supports multi-dimensional arrays.
# Provides mathematical, statistical, and linear algebra functions.
# Forms the foundation for libraries such as:

In [7]:
# 2 

num = [1,2,3,4]

result = []

for x in num:
   
    result.append(x*2)
print(result)


# Numpy

import numpy as np

arr = np.array([1,2,3,4])

result = (arr*2)
print(result)


[2, 4, 6, 8]
[2 4 6 8]


In [21]:
# 3

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("dim : ",arr.ndim)

matrix = np.arange(1, 10).reshape(3, 3)
print(" Matrix:")
print(matrix)

add = matrix + matrix
print("\naddition : ", add)


mul = matrix * matrix
print("\nmultiplication : ", mul)

reshaped = arr.reshape(2, 5)
print("\nReshaped Array (2×5):")
print(reshaped)

dim :  1
 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

addition :  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

multiplication :  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Reshaped Array (2×5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
# 4 

marks = np.array([45,56,67,78,89])

print("marks : ",marks)

print("mean : ",np.mean(marks))
print("median : ",np.median(marks))
print("standard Deviation :",np.std(marks))
print("maximum : ",np.max(marks))
print("minimum : ",np.min(marks))
print("sort :",np.sort(marks))

marks :  [45 56 67 78 89]
mean :  67.0
median :  67.0
standard Deviation : 15.556349186104045
maximum :  89
minimum :  45
sort : [45 56 67 78 89]


In [38]:
# 5

arr = np.array([10,20,30,40,50,60,70,80])

print(arr[:4])
print("alternate element: ",arr[::2])
print(arr[::-1])
arr[arr > 50] = 0
print(arr)

[10 20 30 40]
alternate element:  [10 30 50 70]
[80 70 60 50 40 30 20 10]
[10 20 30 40 50  0  0  0]
